theme: jekyll-theme-time-machine
title: Shayla's Virtual Resume
description: A compiled resume displaying Shayla's overall education, skills, and work history as well as a compilation of relevant links.
show_downloads: false
