theme: jekyll-theme-time-machine
title: Shayla's Virtual Resume
description: A compiled resume displaying Shayla's overall education, skills, and career, as well as a compilation of links to related content.
